version: '3.7'

services:
  tamara-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: tamara-api
    environment: 
      PORT: "${PORT}"
      NODE_ENV: 'development'
    expose:
      - "${PORT}"
    ports:
      - "${PORT}:${PORT}"
    command: yarn dev 
