version: "3.7"

services:
  db:
    image: postgres
    container_name: tamara-db 
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - '5432:5432'

  tamara-api:
    container_name: tamara-api
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    depends_on:
      - db
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: tamara-api
    environment:
      PORT: "${PORT}"
      NODE_ENV: "development"
      NODE_PATH: "/home/node/app"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      DOCKER: 'true'
    ports:
      - "${PORT}:${PORT}"
    command: yarn dev
